import type { BoardTodo } from "./adapt";

const TRACKER = "claude-usage-tracker-windows";
const LANDING = "adv-landing-builder";
const PROCESS = "process";

export const board: BoardTodo[] = [
    {
        id: "tasks#spec-registry",
        subject: "Реестр спек и поле spec задачи",
        status: "done",
        project: TRACKER,
        links: ["tasks#changes", "tasks#model", "process#language"],
    },
    {
        id: "tasks#changes",
        subject: "Change: дельта к спеке",
        status: "done",
        project: TRACKER,
        links: ["tasks#spec-registry"],
    },
    {
        id: "tasks#done-gate",
        subject: "Инварианты закрытия",
        status: "in_progress",
        project: TRACKER,
        links: ["tasks#kind"],
    },
    {
        id: "tasks#model",
        subject: "Модель и хранение задач",
        status: "done",
        project: TRACKER,
    },
    {
        id: "tasks#kind",
        subject: "Kind: авторитет закрытия",
        status: "done",
        project: TRACKER,
    },
    {
        id: "process#language",
        subject: "Язык процесса",
        status: "in_progress",
        project: PROCESS,
        links: ["process#outcome"],
    },
    {
        id: "process#outcome",
        subject: "Метрики исхода",
        status: "queue",
        project: PROCESS,
    },
    {
        id: "blocks#contract",
        subject: "Контракт блока лендинга",
        status: "in_progress",
        project: LANDING,
    },

    {
        id: "t337",
        number: 337,
        subject: "Спека как носитель состояния",
        description:
            "От жанра руками — к механике трекера. Реестр заводится в t#339, перенос спек — t#348, показ вкладкой — t#346.",
        status: "in_progress",
        change: true,
        project: TRACKER,
        links: ["tasks#spec-registry"],
    },
    {
        id: "t338",
        number: 338,
        subject: "Ревизия жанра спек",
        description: "Критерии решения 2026-07-21, дальше жанр переезжает в t#344.",
        status: "done",
        project: TRACKER,
        links: ["t337"],
    },
    {
        id: "t339",
        number: 339,
        subject: "Реестр спек в CLI и линк задача↔секция",
        description: "Валидация якоря, дальше линт путей t#350 и прогон t#351.",
        status: "done",
        kind: "auto",
        project: TRACKER,
        links: ["tasks#spec-registry", "tasks#model"],
    },
    {
        id: "t340",
        number: 340,
        subject: "Впрыск текста секции в контекст задачи",
        status: "queue",
        project: TRACKER,
        links: ["t345"],
    },
    {
        id: "t341",
        number: 341,
        subject: "stop-hook требует дельту спеки",
        description: "Либо дельта, либо явное «spec unchanged» — строгость доводится в t#352.",
        status: "in_progress",
        kind: "auto",
        project: TRACKER,
        links: ["t337", "tasks#done-gate"],
    },
    {
        id: "t342",
        number: 342,
        subject: "Советник-матч задачи против секций спек",
        status: "queue",
        kind: "auto",
        project: TRACKER,
        links: ["t339", "tasks#spec-registry"],
    },
    {
        id: "t344",
        number: 344,
        subject: "Жанр спек на SDD-разделы и адресация секций",
        status: "done",
        project: TRACKER,
        links: ["tasks#spec-registry"],
    },
    {
        id: "t345",
        number: 345,
        subject: "Тема → change, ссылка на спеку",
        description: "Впрыск текста секции остаётся за t#340.",
        status: "in_progress",
        kind: "auto",
        project: TRACKER,
        links: ["t337", "t339"],
    },
    {
        id: "t346",
        number: 346,
        subject: "Спеки вкладкой в окне Tasks",
        status: "in_progress",
        project: TRACKER,
        links: ["t337", "process#language"],
    },
    {
        id: "t347",
        number: 347,
        subject: "Первый живой change по новой механике",
        status: "queue",
        project: TRACKER,
        links: ["t337"],
    },
    {
        id: "t348",
        number: 348,
        subject: "Перенос спек в форму <домен>/spec.md",
        description: "Метаданные раздела переезжают к заголовку в t#349.",
        status: "done",
        project: TRACKER,
        links: ["tasks#spec-registry"],
    },
    {
        id: "t349",
        number: 349,
        subject: "Метаданные раздела к заголовку",
        description: "Реестр читает их из одного источника — t#339.",
        status: "in_progress",
        project: TRACKER,
        links: ["t348"],
    },
    {
        id: "t350",
        number: 350,
        subject: "lint проверяет пути и упомянутые файлы",
        status: "queue",
        project: TRACKER,
        links: ["t339", "tasks#spec-registry"],
    },
    {
        id: "t351",
        number: 351,
        subject: "spec lint в CI и stop-хуке",
        status: "queue",
        project: TRACKER,
        links: ["t339", "t350"],
    },
    {
        id: "t352",
        number: 352,
        subject: "updated требует фактической правки",
        status: "queue",
        project: TRACKER,
        links: ["t341", "tasks#done-gate"],
    },
    {
        id: "t353",
        number: 353,
        subject: "Связь change'ей с разделами",
        description: "Показ живёт в той же вкладке, что и t#346.",
        status: "queue",
        project: TRACKER,
        links: ["t339"],
    },
    {
        id: "t354",
        number: 354,
        subject: "Дельта спеки самим change'ем",
        description: "Первый живой прогон — t#347, корень темы — t#337.",
        status: "queue",
        change: true,
        project: TRACKER,
        links: ["t337", "tasks#changes"],
    },
    {
        id: "t355",
        number: 355,
        subject: "Хвост дорожки без открытых зависимостей",
        status: "queue",
        project: TRACKER,
        links: ["t354"],
    },
    {
        id: "t356",
        number: 356,
        subject: "Экран колец: живой граф ссылок",
        status: "in_progress",
        project: TRACKER,
        links: ["t346", "t339"],
    },
    {
        id: "t357",
        number: 357,
        subject: "Панорама и масштаб холста",
        status: "queue",
        project: TRACKER,
        links: ["t356"],
    },
    {
        id: "t358",
        number: 358,
        subject: "Свёртка чужих проектов в пузырь",
        status: "queue",
        project: TRACKER,
        links: ["t356"],
    },
    {
        id: "t359",
        number: 359,
        subject: "Порог хаба настраивается",
        status: "queue",
        project: TRACKER,
        links: ["t339"],
    },
    {
        id: "t360",
        number: 360,
        subject: "lint реестра проверяет пути и файлы",
        status: "queue",
        project: TRACKER,
        links: ["t347", "t350"],
    },
    {
        id: "t361",
        number: 361,
        subject: "Прогон spec lint там, где он случается",
        status: "queue",
        project: TRACKER,
        links: ["t360"],
    },
    {
        id: "t184",
        number: 184,
        subject: "Свод метрик исхода L3→L4",
        description: "Корень истории — t#337.",
        status: "queue",
        project: TRACKER,
        links: ["process#outcome"],
    },

    {
        id: "t101",
        number: 101,
        subject: "Метрики исхода решения",
        status: "done",
        project: PROCESS,
        links: ["process#outcome"],
    },
    {
        id: "t102",
        number: 102,
        subject: "Храповик решений и дозор",
        status: "in_progress",
        project: PROCESS,
        links: ["process#outcome"],
    },
    {
        id: "t103",
        number: 103,
        subject: "Дистилляция заметок в topics",
        description: "Метрики берутся из t#101.",
        status: "queue",
        project: PROCESS,
        links: ["process#language"],
    },
    {
        id: "t104",
        number: 104,
        subject: "Правила письма: один язык в предложении",
        status: "done",
        project: PROCESS,
        links: ["process#language"],
    },
    {
        id: "t105",
        number: 105,
        subject: "Ретроспектива сессии как жанр",
        description: "Опирается на правила письма t#104.",
        status: "in_progress",
        project: PROCESS,
        links: ["process#language"],
    },
    {
        id: "t106",
        number: 106,
        subject: "Каталог friction по скиллам",
        status: "queue",
        project: PROCESS,
        links: ["t105", "process#outcome"],
    },

    {
        id: "t86",
        number: 86,
        subject: "Zero-блок: разбор вёрстки",
        status: "done",
        project: LANDING,
        links: ["blocks#contract"],
    },
    {
        id: "t132",
        number: 132,
        subject: "B-K0: зафиксировать контракт блока",
        status: "in_progress",
        project: LANDING,
        links: ["blocks#contract"],
    },
    {
        id: "t199",
        number: 199,
        subject: "PoC: воспроизведение Zero-блоков Tilda",
        description: "Разбор вёрстки лежит в t#86.",
        status: "queue",
        project: LANDING,
        links: ["t132"],
    },
    {
        id: "t201",
        number: 201,
        subject: "Каталог блоков: схема данных",
        status: "in_progress",
        project: LANDING,
        links: ["blocks#contract"],
    },
    {
        id: "t202",
        number: 202,
        subject: "Редактор секций: перетаскивание",
        status: "queue",
        project: LANDING,
        links: ["t201"],
    },
    {
        id: "t203",
        number: 203,
        subject: "Импорт лендинга из Tilda",
        description: "Схема данных — t#201.",
        status: "queue",
        project: LANDING,
        links: ["t199"],
    },
    {
        id: "t204",
        number: 204,
        subject: "Тема лендинга: токены и палитра",
        status: "queue",
        project: LANDING,
        links: ["t201"],
    },
    {
        id: "t205",
        number: 205,
        subject: "Экспорт лендинга в статику",
        description: "Спека как носитель состояния — t#337 — задаёт форму раздела.",
        status: "queue",
        project: LANDING,
        links: ["t202"],
    },
    {
        id: "t206",
        number: 206,
        subject: "Превью на мобильном",
        status: "queue",
        project: LANDING,
        links: ["t204"],
    },
    {
        id: "t207",
        number: 207,
        subject: "Сборка блока из пресета",
        status: "queue",
        project: LANDING,
        links: ["blocks#contract", "t201"],
    },
    {
        id: "t208",
        number: 208,
        subject: "Публикация на поддомен",
        status: "queue",
        project: LANDING,
        links: ["t205"],
    },
    {
        id: "t209",
        number: 209,
        subject: "Метрики просмотров лендинга",
        description: "Свод метрик исхода — t#184.",
        status: "queue",
        project: LANDING,
        links: ["t208"],
    },
    {
        id: "t210",
        number: 210,
        subject: "A/B-тест заголовков",
        status: "queue",
        project: LANDING,
        links: ["t209"],
    },
];
