import type { RunGraphNode } from "../../graphModel";
import type {
    Lane,
    LanePort,
    ProjectBand,
    RingCluster,
    RingLink,
    RingNode,
    FocusRow,
    SpecLane,
    TaskLink,
    TaskNode,
} from "./types";

export type RunDetail = Partial<RunGraphNode> &
    Pick<
        RunGraphNode,
        | "cost"
        | "measurability"
        | "blocks"
        | "task_cost"
        | "unattributed_cost"
        | "agents"
    >;

export const lanes: Lane[] = [
    {
        id: "t337",
        kicker: "тема · change #337",
        title: "Спека как носитель состояния",
        note: "от жанра руками — к механике трекера",
        progress: 0.42,
        progressLabel: "5 / 12 готово · волны 1–5",
        cost: "$94.10",
        duration: "14ч 20м",
        tone: "theme",
        ports: [
            { side: "right", label: "в дорожку", sub: "#354 · 2 связи" },
        ] as LanePort[],
        artifactSummary: ["4 раздела · 7 обещанных файлов · 5 прогонов"],
    },
    {
        id: "t354",
        kicker: "тема · change #354",
        title: "Дельта спеки самим change'ем",
        progress: 0.12,
        progressLabel: "1 / 8 готово · заблокирована",
        cost: "$18.40",
        duration: "3ч 05м",
        tone: "theme",
        ports: [{ side: "left", label: "из дорожки", sub: "#337" }] as LanePort[],
        tail: {
            label: "3 / 5 свёрнуто",
            note: "хвост дорожки без открытых зависимостей — раскрыть",
        },
    },
    {
        id: "t320",
        kicker: "тема · change #320",
        title: "Ночной триаж доски",
        note: "разбор просрочек по расписанию",
        progress: 1,
        progressLabel: "4 / 4 готово · волны 1–2",
        cost: "$21.30",
        duration: "5ч 10м",
        tone: "theme",
        done: true,
    },
    {
        id: "free",
        kicker: "без темы",
        title: "Свободные задачи",
        note: "не привязаны к change'у",
        tone: "plain",
        more: { text: "+ ещё 62 задачи без темы ·", action: "сгруппировать" },
    },
];

export const projects: ProjectBand[] = [
    {
        name: "claude-usage-tracker-windows",
        tasks: "21 задача",
        cost: "$146.80",
        lanes: ["t337", "t354", "t320"],
    },
    {
        name: "adv-landing-builder",
        tasks: "64 задачи",
        cost: "$37.40",
        lanes: ["free"],
    },
];

export const tasks: TaskNode[] = [
    {
        id: "#338",
        title: "Провожу ревизию жанра спек по критериям решения 2026-07-21…",
        status: "ready",
        done: true,
        wave: 1,
        lane: "t337",
        cost: "$6.20",
        costShare: 0.18,
    },
    {
        id: "#344",
        title: "Перевожу жанр спек на SDD-разделы и задаю адресацию секций",
        status: "ready",
        done: true,
        wave: 1,
        lane: "t337",
        cost: "$11.40",
        costShare: 0.32,
    },
    {
        id: "#339",
        title: "Завожу в CLI реестр спек и линк задача↔секция с валидацией якоря",
        status: "ready",
        done: true,
        auto: true,
        wave: 2,
        lane: "t337",
        cost: "$18.90",
        costShare: 0.55,
        ports: [
            { dir: "R", kind: "spec", label: "spec#registry" },
            { dir: "W", kind: "file", label: "spec.mjs" },
        ],
    },
    {
        id: "#348",
        title: "Переношу существующие спеки в форму <домен>/spec.md",
        status: "ready",
        done: true,
        wave: 2,
        lane: "t337",
        cost: "$9.80",
        costShare: 0.28,
        ports: [
            { dir: "R", kind: "spec", label: "spec#registry" },
            { dir: "W", kind: "file", label: "docs/specs/**" },
        ],
    },
    {
        id: "#349",
        title: "Переношу метаданные раздела из шапки к заголовку — один источник",
        status: "ready",
        wave: 3,
        lane: "t337",
        cost: "$4.10",
        costShare: 0.12,
        ports: [
            { dir: "R", kind: "file", label: "docs/specs/**" },
            { dir: "W", kind: "spec", label: "spec#registry" },
        ],
    },
    {
        id: "#345",
        title: "Переименовываю тему в change и вешаю на неё ссылку на спеку",
        status: "waiting",
        auto: true,
        active: true,
        selected: true,
        wave: 3,
        lane: "t337",
        cost: "$21.60",
        costShare: 0.62,
        runs: 3,
        ports: [
            { dir: "R", kind: "file", label: "spec.mjs" },
            { dir: "R", kind: "spec", label: "spec#registry" },
            { dir: "W", kind: "file", label: "todos.rs" },
            { dir: "W", kind: "spec", label: "spec#changes" },
        ],
    },
    {
        id: "#341",
        title: "Учу stop-hook требовать дельту спеки или явное «spec unchanged»",
        status: "ready",
        auto: true,
        active: true,
        wave: 4,
        lane: "t337",
        cost: "$14.30",
        costShare: 0.41,
        ports: [
            { dir: "R", kind: "spec", label: "spec#changes" },
            { dir: "R", kind: "handoff", label: "handoff #345" },
            { dir: "W", kind: "file", label: "stop.mjs" },
        ],
    },
    {
        id: "#350",
        title: "lint проверяет упомянутые пути и файлы",
        status: "waiting",
        wave: 4,
        lane: "t337",
        cost: "неизвестно",
        costKnown: false,
        costNote: "не бралась",
        ports: [
            { dir: "R", kind: "spec", label: "spec#registry" },
            { dir: "W", kind: "file", label: "render.ts", exists: false },
        ],
    },
    {
        id: "#346",
        title: "Показываю спеки вкладкой в окне Tasks — спека, её change'и, граф",
        status: "waiting",
        active: true,
        wave: 5,
        lane: "t337",
        cost: "$7.80",
        costShare: 0.22,
        ports: [
            { dir: "R", kind: "file", label: "todos.rs" },
            { dir: "R", kind: "spec", label: "spec#changes" },
        ],
    },
    {
        id: "#351",
        title: "Ставлю прогон spec lint туда, где он случается",
        status: "blocked",
        wave: 5,
        lane: "t337",
        cost: "неизвестно",
        costKnown: false,
        costNote: "не бралась",
        ports: [{ dir: "R", kind: "file", label: "stop.mjs" }],
        warn: "не пишет spec",
    },

    {
        id: "#347",
        title: "Провожу первый живой change по новой механике — перекраиваю спеку",
        status: "blocked",
        wave: 1,
        lane: "t354",
        cost: "$18.40",
        costShare: 0.71,
    },
    {
        id: "#360",
        title: "Учу lint реестра проверять, что упомянутые пути и файлы есть",
        status: "waiting",
        wave: 2,
        lane: "t354",
        cost: "неизвестно",
        costKnown: false,
        costNote: "не бралась",
    },
    {
        id: "#361",
        title: "Ставлю прогон spec lint туда, где он случается",
        status: "blocked",
        wave: 3,
        lane: "t354",
        cost: "неизвестно",
        costKnown: false,
        costNote: "не бралась",
    },
    {
        id: "#352",
        title: "Учу ответ updated требовать фактической правки",
        status: "blocked",
        wave: 3,
        lane: "t354",
        cost: "неизвестно",
        costKnown: false,
        costNote: "не бралась",
    },
    {
        id: "#342",
        title: "Строю советник-матч задачи против секций спек",
        status: "blocked",
        auto: true,
        wave: 4,
        lane: "t354",
        cost: "неизвестно",
        costKnown: false,
        costNote: "не бралась",
    },
    {
        id: "#353",
        title: "Показываю связь change'ей с разделами",
        status: "blocked",
        wave: 4,
        lane: "t354",
        cost: "неизвестно",
        costKnown: false,
        costNote: "не бралась",
    },

    {
        id: "#321",
        title: "Ставлю планировщик триажа внутрь трекера",
        status: "done",
        done: true,
        wave: 1,
        lane: "t320",
        cost: "$9.40",
        costShare: 0.44,
    },
    {
        id: "#322",
        title: "Экспортирую доску для разбора детерминированным шагом",
        status: "done",
        done: true,
        wave: 1,
        lane: "t320",
        cost: "$5.10",
        costShare: 0.24,
    },
    {
        id: "#323",
        title: "Публикую сводку разбора обратно в доску",
        status: "done",
        done: true,
        wave: 2,
        lane: "t320",
        cost: "$6.80",
        costShare: 0.32,
    },
    {
        id: "#132",
        title: "B-K0: зафиксировать контракт блока",
        status: "waiting",
        wave: 1,
        lane: "free",
        cost: "$12.10",
        costShare: 0.4,
    },
    {
        id: "#199",
        title: "PoC: воспроизведение Zero-блоков Tilda",
        status: "blocked",
        wave: 2,
        lane: "free",
        cost: "неизвестно",
        costKnown: false,
        costNote: "не бралась",
    },
];

export const links: TaskLink[] = [
    { from: "#338", to: "#339" },
    { from: "#344", to: "#339" },
    { from: "#344", to: "#348" },
    {
        from: "#339",
        to: "#345",
        artifact: {
            kind: "file",
            address: "scripts/cli/spec.mjs",
            short: "spec.mjs",
            exists: true,
        },
    },
    {
        from: "#348",
        to: "#349",
        artifact: {
            kind: "file",
            address: "docs/specs/**",
            short: "docs/specs/**",
            exists: true,
        },
    },
    {
        from: "#345",
        to: "#341",
        artifact: {
            kind: "spec",
            address: "tasks#changes",
            short: "spec#changes",
            exists: true,
        },
    },
    {
        from: "#349",
        to: "#350",
        artifact: {
            kind: "spec",
            address: "tasks#spec-registry",
            short: "spec#registry",
            exists: true,
        },
    },
    {
        from: "#341",
        to: "#346",
        artifact: {
            kind: "handoff",
            address: "handoff #345",
            short: "handoff #345",
            exists: true,
        },
    },
    {
        from: "#350",
        to: "#351",
        artifact: { kind: "after", address: "after", short: "after", exists: true },
    },
    { from: "#341", to: "#347" },
    { from: "#346", to: "#347" },
    { from: "#347", to: "#360" },
    { from: "#360", to: "#361" },
    { from: "#360", to: "#352" },
    { from: "#361", to: "#342" },
    { from: "#352", to: "#353" },
    { from: "#321", to: "#323" },
    { from: "#322", to: "#323" },
    { from: "#132", to: "#199" },
];

export const runDetails: Record<string, RunDetail> = {
    "#338": {
        cost: 6.2,
        task_cost: 6.2,
        unattributed_cost: null,
        duration_minutes: 41,
        duration_calendar: false,
        measurability: "measured",
        blocks: 1,
        tokens: 380000,
        messages: 74,
        tool_calls: 52,
        tool_errors: 0,
        agents: [
            {
                agent_id: null,
                agent_type: null,
                description: null,
                cost: 6.2,
                messages: 74,
            },
        ],
    },
    "#344": {
        cost: 11.4,
        task_cost: 12.05,
        unattributed_cost: 0.65,
        duration_minutes: 68,
        duration_calendar: false,
        measurability: "measured",
        blocks: 2,
        tokens: 720000,
        messages: 129,
        tool_calls: 96,
        tool_errors: 2,
        agents: [
            {
                agent_id: null,
                agent_type: null,
                description: null,
                cost: 8.6,
                messages: 97,
            },
            {
                agent_id: "ag_4b1e77",
                agent_type: "general-purpose",
                description: "Переношу разделы в SDD-форму",
                cost: 2.8,
                messages: 32,
            },
        ],
    },
    "#339": {
        cost: 18.9,
        task_cost: 19.4,
        unattributed_cost: 0.5,
        duration_minutes: 124,
        duration_calendar: false,
        measurability: "measured",
        blocks: 2,
        tokens: 1460000,
        messages: 233,
        tool_calls: 204,
        tool_errors: 6,
        agents: [
            {
                agent_id: null,
                agent_type: null,
                description: null,
                cost: 18.9,
                messages: 233,
            },
        ],
    },
    "#348": {
        cost: 9.8,
        task_cost: 9.8,
        unattributed_cost: null,
        duration_minutes: 52,
        duration_calendar: false,
        measurability: "measured",
        blocks: 1,
        tokens: 610000,
        messages: 98,
        tool_calls: 77,
        tool_errors: 1,
        agents: [
            {
                agent_id: null,
                agent_type: null,
                description: null,
                cost: 9.8,
                messages: 98,
            },
        ],
    },
    "#349": {
        cost: null,
        task_cost: 4.1,
        unattributed_cost: null,
        duration_minutes: null,
        duration_calendar: false,
        measurability: "empty_blocks",
        blocks: 1,
        tokens: null,
        messages: null,
        tool_calls: null,
        tool_errors: null,
        agents: [],
    },
    "#345": {
        cost: 21.6,
        task_cost: 24.85,
        unattributed_cost: 1.1,
        duration_minutes: 96,
        duration_calendar: false,
        measurability: "measured",
        blocks: 3,
        tokens: 1284000,
        messages: 214,
        tool_calls: 168,
        tool_errors: 4,
        agents: [
            {
                agent_id: null,
                agent_type: null,
                description: null,
                cost: 14.2,
                messages: 138,
            },
            {
                agent_id: "ag_7f21c4",
                agent_type: "general-purpose",
                description: "Правлю поле change в todos.rs и CLI",
                cost: 4.9,
                messages: 46,
            },
            {
                agent_id: "ag_c93b08",
                agent_type: "Explore",
                description: "Ищу упоминания темы в хуках и спеках",
                cost: 2.5,
                messages: 30,
            },
        ],
    },
    "#341": {
        cost: 14.3,
        task_cost: 15.6,
        unattributed_cost: 0.55,
        duration_minutes: 71,
        duration_calendar: false,
        measurability: "measured",
        blocks: 2,
        tokens: 902000,
        messages: 156,
        tool_calls: 121,
        tool_errors: 1,
        agents: [
            {
                agent_id: null,
                agent_type: null,
                description: null,
                cost: 11.1,
                messages: 121,
            },
            {
                agent_id: "ag_18d0aa",
                agent_type: "general-purpose",
                description: "Пишу тесты stop-хука на дельту спеки",
                cost: 3.2,
                messages: 35,
            },
        ],
    },
    "#350": {
        cost: null,
        task_cost: null,
        unattributed_cost: null,
        duration_minutes: null,
        duration_calendar: false,
        measurability: "no_in_progress",
        blocks: 0,
        tokens: null,
        messages: null,
        tool_calls: null,
        tool_errors: null,
        agents: [],
    },
    "#346": {
        cost: null,
        task_cost: 7.8,
        unattributed_cost: null,
        duration_minutes: null,
        duration_calendar: false,
        measurability: "no_blocks",
        blocks: 0,
        tokens: null,
        messages: null,
        tool_calls: null,
        tool_errors: null,
        agents: [],
    },
    "#351": {
        cost: null,
        task_cost: null,
        unattributed_cost: null,
        duration_minutes: null,
        duration_calendar: false,
        measurability: "no_in_progress",
        blocks: 0,
        tokens: null,
        messages: null,
        tool_calls: null,
        tool_errors: null,
        agents: [],
    },
};

function reach(id: string, up: boolean, edges: TaskLink[]): Set<string> {
    const seen = new Set<string>([id]);
    const stack = [id];
    while (stack.length) {
        const from = stack.pop() as string;
        for (const link of edges) {
            if (up ? link.to !== from : link.from !== from) continue;
            const next = up ? link.from : link.to;
            if (seen.has(next)) continue;
            seen.add(next);
            stack.push(next);
        }
    }
    return seen;
}

export function chainOf(id: string, edges: TaskLink[] = links): Set<string> {
    if (!id) return new Set<string>();
    return new Set([...reach(id, true, edges), ...reach(id, false, edges)]);
}

export const wireLegend = [
    { tone: "spec", text: "по проводу течёт раздел спеки" },
    { tone: "file", text: "файл" },
    { tone: "handoff", text: "эстафета change’а (handoff)" },
    { tone: "after", text: "серый — связь без артефакта (после/after)" },
];

export const specLanes: SpecLane[] = [
    {
        id: "spec-registry",
        kicker: "раздел спеки",
        address: "tasks#spec-registry",
        title: "Реестр спек и поле spec задачи",
        note: "Реестр спек и поле spec задачи",
        part: "часть: устройство  обновлён 03.08",
        prose:
            "Адрес раздела — <домен>#<слаг>. Поле spec задачи — структурная замена текстовой пометки внутри description.",
        lintLabel: "lint чист · 112 / 120 строк",
        lintTone: "ok",
        metrics: ["11 ссылок", "4 change'а"],
        chips: [
            { text: "4 change'а", tone: "theme" },
            { text: "lint чист", tone: "ok" },
        ],
        tone: "spec",
        incoming: [
            { id: "#339", title: "Реестр спек в CLI и линк задача↔секция", state: "в работе" },
            { id: "#345", title: "Тема → change, ссылка на спеку", state: "в работе" },
            { id: "#350", title: "lint проверяет пути и упомянутые файлы", state: "очередь" },
        ],
        outgoing: [
            { id: "tasks#changes", title: "Change: дельта к спеке", tone: "spec" },
            { id: "tasks#model", title: "Модель и хранение", tone: "spec" },
            { id: "process#language", title: "Язык процесса · другой домен", tone: "spec" },
        ],
        files: [
            { path: "scripts/cli/spec.mjs", anchor: "#реестр", exists: true },
            { path: "docs/specs/tasks/spec.md", anchor: "#адресация", exists: true },
            { path: "src-tauri/src/todos.rs", anchor: "#поле-spec", exists: true },
            {
                path: "insightHelp/render.ts",
                anchor: "#линт",
                exists: false,
                note: "не найден",
            },
        ],
    },
    {
        id: "done-gate",
        kicker: "раздел спеки · внимание",
        address: "tasks#done-gate",
        title: "Инварианты закрытия",
        note: "Инварианты закрытия",
        part: "часть: инварианты",
        partWarn: "за потолком прозы",
        lintLabel: "128 / 120 строк · 2 change'а",
        lintTone: "warn",
        metrics: ["6 ссылок", "2 change'а"],
        tone: "warn",
        incoming: [
            { id: "#341", title: "stop-hook требует дельту спеки", state: "в работе" },
            { id: "#352", title: "updated требует фактической правки", state: "очередь" },
        ],
        outgoing: [{ id: "tasks#kind", title: "Kind: авторитет закрытия", tone: "spec" }],
        files: [
            { path: "scripts/hooks/stop.mjs", anchor: "#гейт", exists: true },
            { path: "src-tauri/src/gate.rs", anchor: "#ответ", exists: true },
        ],
    },
    {
        id: "orphan",
        kicker: "вне разделов",
        address: "",
        title: "Ссылки задача → задача",
        note: "не привязаны к спеке",
        tone: "plain",
        incoming: [{ id: "#184", title: "Свод метрик исхода L3→L4" }],
        outgoing: [
            {
                id: "#86",
                title: "adv-landing-builder · задача другого проекта",
                tone: "external",
            },
        ],
        files: [],
        more: { text: "+ 62 ссылки без раздела ·", action: "сгруппировать по проекту" },
    },
];

export const orphanMiddle = {
    id: "#101 · #102 · #103",
    title: "Метрики исхода, храповика и дистилляции",
};

export const ringFocus: RingNode = {
    id: "#337",
    label: "тема · change #337",
    title: "Спека как носитель состояния",
    ring: 0,
    angle: 0,
    radius: 0,
    tone: "focus",
    badge: "12 задач  15 ссылок",
    counter: "$94.10",
};

export const ringNodes: RingNode[] = [
    {
        id: "#339",
        label: "#339 · хаб · 7 ↵",
        title: "Реестр спек в CLI и линк задача↔секция",
        ring: 1,
        angle: 0,
        radius: 266,
        tone: "hub",
    },
    {
        id: "tasks#spec-registry",
        label: "tasks#spec-registry",
        title: "Раздел спеки · 6 ↵",
        ring: 1,
        angle: 236,
        radius: 186,
        tone: "spec",
        counter: "1",
    },
    {
        id: "#346",
        label: "#346",
        title: "Спеки вкладкой в окне Tasks",
        ring: 1,
        angle: 295,
        radius: 177,
    },
    {
        id: "#348",
        label: "#348",
        title: "Перенос спек в <домен>/spec.md",
        ring: 1,
        angle: 180,
        radius: 270,
    },
    {
        id: "#345",
        label: "#345",
        title: "Тема → change, ссылка на спеку",
        ring: 1,
        angle: 56,
        radius: 179,
    },
    {
        id: "#341",
        label: "#341",
        title: "stop-hook требует дельту спеки",
        ring: 1,
        angle: 113,
        radius: 187,
    },
    {
        id: "#338",
        label: "#338",
        title: "Ревизия жанра спек",
        ring: 2,
        angle: 253,
        radius: 346,
        dashed: true,
    },
    {
        id: "process#language",
        label: "process#language",
        title: "Раздел спеки процесса",
        ring: 2,
        angle: 285,
        radius: 334,
        tone: "spec",
        counter: "9 ссылок",
        dashed: true,
    },
    {
        id: "#344",
        label: "#344",
        title: "Жанр спек на SDD-разделы",
        ring: 2,
        angle: 204,
        radius: 353,
        dashed: true,
    },
    {
        id: "#351",
        label: "#351",
        title: "spec lint в CI и stop-хук",
        ring: 2,
        angle: 331,
        radius: 337,
        dashed: true,
    },
    {
        id: "#349",
        label: "#349",
        title: "Метаданные к заголовку",
        ring: 2,
        angle: 165,
        radius: 351,
        dashed: true,
    },
    {
        id: "#350",
        label: "#350",
        title: "lint проверяет пути и файлы",
        ring: 2,
        angle: 27,
        radius: 325,
        dashed: true,
    },
    {
        id: "#352",
        label: "#352",
        title: "updated требует правки",
        ring: 2,
        angle: 131,
        radius: 351,
        dashed: true,
    },
    {
        id: "#340",
        label: "#340",
        title: "Впрыск текста секции",
        ring: 2,
        angle: 71,
        radius: 342,
        dashed: true,
    },
];

export const ringLinks: RingLink[] = [
    { from: "#337", to: "#339" },
    { from: "#337", to: "#348" },
    { from: "#337", to: "tasks#spec-registry" },
    { from: "#337", to: "#346" },
    { from: "#337", to: "#345" },
    { from: "#337", to: "#341" },
    { from: "#339", to: "#350", dashed: true },
    { from: "#339", to: "#351", dashed: true },
    { from: "tasks#spec-registry", to: "#338", dashed: true },
    { from: "tasks#spec-registry", to: "#344", dashed: true },
    { from: "#346", to: "process#language", dashed: true },
    { from: "#348", to: "#349", dashed: true },
    { from: "#341", to: "#352", dashed: true },
    { from: "#345", to: "#340", dashed: true },
];

export const ringClusters: RingCluster[] = [
    { id: "process", title: "process", note: "19 узлов", x: 0.164, y: 0.2, size: 96 },
    {
        id: "agent-sdk",
        title: "agent-sdk",
        note: "внешний домен · 11",
        x: 0.775,
        y: 0.278,
        size: 92,
    },
    {
        id: "adv-landing",
        title: "adv-landing builder",
        note: "64 узла · 3 связи сюда",
        x: 0.761,
        y: 0.546,
        size: 112,
    },
];

export const focusOut: FocusRow[] = [
    { id: "#339", title: "Реестр спек в CLI", count: 1 },
    { id: "#348", title: "Перенос спек в форму", count: 1 },
    { id: "spec", title: "tasks#spec-registry", count: 1, kind: "spec" },
    { id: "#346", title: "Спеки вкладкой в Tasks", count: 1 },
];

export const focusIn: FocusRow[] = [
    { id: "#345", title: "Тема → change", count: 1 },
    { id: "#341", title: "stop-hook требует дельту", count: 1 },
    { id: "#354", title: "Дельта спеки change'ем", count: 2 },
];

export const graphStats = {
    nodes: "418 узлов",
    focus: "12 в фокусе",
    collapsed: "406 свёрнуто",
    active: "85 активных",
    spend: "$184.20 за 7 дней",
    refs: "418 узлов · 96 ссылок · 24 раздела",
    artifacts: "12 задач · 21 переход артефактов",
};
