<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import ProjectLabel from "../kernel/ProjectLabel.vue";
import type { TodoCardRow } from "./todoFilter";
const props = defineProps<{ todo: TodoCardRow; dragging?: boolean; color: string }>();
const emit = defineEmits<{ dragstart: [DragEvent]; dragend: []; move: [string]; open: []; remove: []; openSpec: [string] }>();
const { t } = useI18n();
const priority = computed(() => props.todo.priority === "high" ? t("todoPriorityHigh") : props.todo.priority === "medium" ? t("todoPriorityMedium") : t("todoPriorityLow"));
const fmtCost = (cost: number) => "$" + (cost >= 100 ? Math.round(cost) : cost.toFixed(2));
</script>
<template><article class="tw-card" :class="{ dragging, done: todo.status === 'done' }" :style="{ borderLeftColor: color }" draggable="true" @dragstart="emit('dragstart', $event)" @dragend="emit('dragend')"><div class="tw-card-title"><span v-if="todo.number" class="tw-card-num">#{{ todo.number }}</span>{{ todo.subject }}</div><p v-if="todo.description" class="tw-card-desc">{{ todo.description }}</p><div class="tw-card-meta"><span v-if="todo.priority" class="tw-chip tw-prio" :class="'tw-prio-' + todo.priority">{{ priority }}</span><span v-if="todo.created_by === 'claude'" class="tw-ai sm">{{ t('todoAi') }}</span><span v-if="todo.project" class="tw-tag"><ProjectLabel :name="todo.project" :aliases="todo.aliases" :merged-into="todo.mergedInto" /></span><span v-if="todo.from && todo.from !== todo.project" class="tw-chip tw-from">↘ {{ t('todoFrom') }} {{ todo.from }}</span><span v-if="todo.importedAt" class="tw-chip tw-imported" :title="t('todoImportedHint')">⤓ {{ t('todoImported') }}</span><span v-if="todo.scheduled_for" class="tw-chip">📅 {{ todo.scheduled_for }}</span><span v-if="todo.hasPlan" class="tw-chip" :title="t('todoPlan')">📝</span><button v-for="address in todo.spec" :key="address" class="tw-chip tw-spec" :title="t('todoSpecHint')" @click.stop="emit('openSpec', address)">📘 {{ address }}</button><span v-if="todo.refCount" class="tw-chip" :title="t('todoRefs')">🔗 {{ todo.refCount }}</span><span v-if="todo.cost != null" class="tw-chip" :title="todo.costTitle">⚡ {{ fmtCost(todo.cost) }}</span></div><div class="tw-card-foot"><select :value="todo.status" class="tw-select sm" @click.stop @mousedown.stop @change="emit('move', ($event.target as HTMLSelectElement).value)"><option value="backlog">{{ t('colBacklog') }}</option><option value="queue">{{ t('colQueue') }}</option><option value="in_progress">{{ t('statusInProgress') }}</option><option value="review">{{ t('colReview') }}</option><option value="done">{{ t('statusDone') }}</option></select><div class="tw-card-actions"><button class="tw-icon" :title="t('todoEdit')" @click.stop="emit('open')">✎</button><button class="tw-icon danger" :title="t('todoDelete')" @click.stop="emit('remove')">×</button></div></div></article></template>
