//! User-owned Todo store for the in-app task manager.
//!
//! The tracker is the SOURCE OF TRUTH: the user creates/edits todos in the app,
//! they're persisted as a single `todos.json` in the app data dir, and a Claude
//! Code SessionStart hook reads that file to surface the active todos for the
//! current project. Claude may flip a todo's `status` (and, on explicit request,
//! edit details) by rewriting the same file — hence a plain, self-contained JSON
//! schema rather than a DB table: an external hook can read it without sqlite,
//! and edits stay diff-friendly.
//!
//! JSON is snake_case to match the rest of the app's wire format (analytics /
//! config). Writes are atomic (temp file + rename) so a crash mid-write can't
//! corrupt the list shared between the tracker and Claude.

use std::path::Path;

use serde::{Deserialize, Serialize};

/// One user todo. `id` is generated by the frontend (a stable opaque string).
/// `status` is one kanban column: `backlog` | `queue` | `in_progress` |
/// `review` | `done`. The pre-kanban `pending` status is migrated to `backlog`
/// on load (see [`canonical_status`]). Optional fields are omitted from the file
/// when empty to keep hand-edits readable.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Todo {
    pub id: String,
    pub subject: String,
    #[serde(default)]
    pub description: String,
    pub status: String,
    /// LLM/user time estimate in minutes; None = unestimated.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub estimate_minutes: Option<i64>,
    /// ISO date `YYYY-MM-DD` the user plans to do this; None = unscheduled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduled_for: Option<String>,
    /// Raw plan — written by the USER, never generated by the LLM.
    #[serde(default)]
    pub plan: String,
    /// Project basename this todo belongs to (matches a transcript cwd
    /// basename); None = not tied to a project.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(default)]
    pub created_at: String,
    #[serde(default)]
    pub updated_at: String,
}

fn default_version() -> u32 {
    1
}

/// The on-disk shape of `todos.json`. `version` lets us migrate the format
/// later; unknown/missing fields default so older or hand-edited files load.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TodoFile {
    #[serde(default = "default_version")]
    pub version: u32,
    #[serde(default)]
    pub todos: Vec<Todo>,
}

impl Default for TodoFile {
    fn default() -> Self {
        TodoFile {
            version: default_version(),
            todos: Vec::new(),
        }
    }
}

/// Read the store. A missing or malformed file yields an empty list rather than
/// an error — the tracker should always present a usable (possibly empty) todo
/// view, and the hook must never fail a session over a bad file. Every loaded
/// status is run through [`canonical_status`] so legacy `pending` rows (written
/// before the kanban columns existed) and any hand-edited values land in a real
/// column instead of vanishing.
pub fn load(path: &Path) -> TodoFile {
    let mut file = match std::fs::read_to_string(path) {
        Ok(s) => serde_json::from_str(&s).unwrap_or_default(),
        Err(_) => TodoFile::default(),
    };
    for t in &mut file.todos {
        t.status = canonical_status(&t.status).to_string();
    }
    file
}

/// Persist the store atomically: write a sibling temp file, then rename over the
/// target (std rename replaces the destination on Windows for files).
pub fn save(path: &Path, file: &TodoFile) -> Result<(), String> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    }
    let json = serde_json::to_string_pretty(file).map_err(|e| e.to_string())?;
    let tmp = path.with_extension("json.tmp");
    std::fs::write(&tmp, json.as_bytes()).map_err(|e| e.to_string())?;
    std::fs::rename(&tmp, path).map_err(|e| e.to_string())?;
    Ok(())
}

/// Insert a new todo or replace an existing one (matched by `id`). `created_at`
/// is preserved from the existing row (or stamped `now` for a new one);
/// `updated_at` is always set to `now`.
pub fn upsert(file: &mut TodoFile, mut todo: Todo, now: &str) {
    todo.updated_at = now.to_string();
    if let Some(existing) = file.todos.iter_mut().find(|t| t.id == todo.id) {
        todo.created_at = if existing.created_at.is_empty() {
            now.to_string()
        } else {
            existing.created_at.clone()
        };
        *existing = todo;
    } else {
        if todo.created_at.is_empty() {
            todo.created_at = now.to_string();
        }
        file.todos.push(todo);
    }
}

/// Remove the todo with this id (no-op if absent).
pub fn delete(file: &mut TodoFile, id: &str) {
    file.todos.retain(|t| t.id != id);
}

/// Set a todo's status and bump `updated_at`. Returns false if no such id.
pub fn set_status(file: &mut TodoFile, id: &str, status: &str, now: &str) -> bool {
    if let Some(t) = file.todos.iter_mut().find(|t| t.id == id) {
        t.status = status.to_string();
        t.updated_at = now.to_string();
        true
    } else {
        false
    }
}

/// The kanban columns, left to right. The frontend mirrors this order; the hook
/// only cares whether a status is `done`.
pub const STATUSES: [&str; 5] = ["backlog", "queue", "in_progress", "review", "done"];

/// Valid status values. Used by the command layer to reject bad input before it
/// reaches the file (which Claude and the hook also read).
pub fn is_valid_status(status: &str) -> bool {
    STATUSES.contains(&status)
}

/// Map a raw status onto a real kanban column. The pre-kanban `pending` status
/// becomes `backlog`; any unrecognized value (a typo, a hand-edit, or a status
/// from a future version) also falls back to `backlog` so the todo still shows
/// up as actionable rather than disappearing from every column.
pub fn canonical_status(status: &str) -> &str {
    if is_valid_status(status) {
        status
    } else {
        "backlog"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn todo(id: &str, status: &str) -> Todo {
        Todo {
            id: id.to_string(),
            subject: format!("subject {id}"),
            description: String::new(),
            status: status.to_string(),
            estimate_minutes: None,
            scheduled_for: None,
            plan: String::new(),
            project: None,
            created_at: String::new(),
            updated_at: String::new(),
        }
    }

    #[test]
    fn upsert_adds_then_updates_in_place() {
        let mut f = TodoFile::default();
        upsert(&mut f, todo("a", "backlog"), "T1");
        assert_eq!(f.todos.len(), 1);
        assert_eq!(f.todos[0].created_at, "T1");
        assert_eq!(f.todos[0].updated_at, "T1");

        // Updating the same id replaces it and preserves created_at.
        let mut updated = todo("a", "done");
        updated.subject = "changed".into();
        upsert(&mut f, updated, "T2");
        assert_eq!(f.todos.len(), 1);
        assert_eq!(f.todos[0].status, "done");
        assert_eq!(f.todos[0].subject, "changed");
        assert_eq!(f.todos[0].created_at, "T1"); // preserved
        assert_eq!(f.todos[0].updated_at, "T2"); // bumped
    }

    #[test]
    fn delete_removes_by_id() {
        let mut f = TodoFile::default();
        upsert(&mut f, todo("a", "backlog"), "T1");
        upsert(&mut f, todo("b", "backlog"), "T1");
        delete(&mut f, "a");
        assert_eq!(f.todos.len(), 1);
        assert_eq!(f.todos[0].id, "b");
        delete(&mut f, "missing"); // no-op
        assert_eq!(f.todos.len(), 1);
    }

    #[test]
    fn set_status_updates_and_reports_missing() {
        let mut f = TodoFile::default();
        upsert(&mut f, todo("a", "backlog"), "T1");
        assert!(set_status(&mut f, "a", "in_progress", "T2"));
        assert_eq!(f.todos[0].status, "in_progress");
        assert_eq!(f.todos[0].updated_at, "T2");
        assert!(!set_status(&mut f, "missing", "done", "T3"));
    }

    #[test]
    fn status_validation() {
        assert!(is_valid_status("backlog"));
        assert!(is_valid_status("queue"));
        assert!(is_valid_status("in_progress"));
        assert!(is_valid_status("review"));
        assert!(is_valid_status("done"));
        // Legacy and bogus values are not accepted at the command layer.
        assert!(!is_valid_status("pending"));
        assert!(!is_valid_status("Done"));
        assert!(!is_valid_status("archived"));
    }

    #[test]
    fn canonical_status_migrates_legacy_and_unknown() {
        assert_eq!(canonical_status("in_progress"), "in_progress");
        assert_eq!(canonical_status("review"), "review");
        // Pre-kanban status and anything unrecognized collapse to backlog.
        assert_eq!(canonical_status("pending"), "backlog");
        assert_eq!(canonical_status("whatever"), "backlog");
    }

    #[test]
    fn load_migrates_legacy_pending_status() {
        let dir = std::env::temp_dir();
        let path = dir.join("cut_todos_migrate_test.json");
        let _ = std::fs::remove_file(&path);

        // A file written before the kanban columns existed: status "pending".
        let raw = r#"{"version":1,"todos":[{"id":"a","subject":"s","status":"pending","plan":""}]}"#;
        std::fs::write(&path, raw).unwrap();

        let f = load(&path);
        assert_eq!(f.todos.len(), 1);
        assert_eq!(f.todos[0].status, "backlog");
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn load_missing_file_is_empty_default() {
        let f = load(Path::new("does-not-exist-12345.json"));
        assert_eq!(f.version, 1);
        assert!(f.todos.is_empty());
    }

    #[test]
    fn save_then_load_roundtrips_and_omits_empty_optionals() {
        let dir = std::env::temp_dir();
        let path = dir.join("cut_todos_roundtrip_test.json");
        let _ = std::fs::remove_file(&path);

        let mut f = TodoFile::default();
        let mut t = todo("a", "queue");
        t.estimate_minutes = Some(30);
        t.project = Some("my-proj".into());
        upsert(&mut f, t, "T1");
        save(&path, &f).unwrap();

        // Optional None fields are skipped in the serialized form.
        let raw = std::fs::read_to_string(&path).unwrap();
        assert!(raw.contains("\"estimate_minutes\": 30"));
        assert!(!raw.contains("scheduled_for"));

        let back = load(&path);
        assert_eq!(back.todos.len(), 1);
        assert_eq!(back.todos[0].estimate_minutes, Some(30));
        assert_eq!(back.todos[0].project.as_deref(), Some("my-proj"));
        let _ = std::fs::remove_file(&path);
    }
}
