//! User-owned Todo store for the in-app task manager.
//!
//! The tracker is the SOURCE OF TRUTH: the user creates/edits todos in the app,
//! they're persisted as a single `todos.json` in the app data dir, and a Claude
//! Code SessionStart hook reads that file to surface the active todos for the
//! current project. Claude may flip a todo's `status` (and, on explicit request,
//! edit details) by rewriting the same file — hence a plain, self-contained JSON
//! schema rather than a DB table: an external hook can read it without sqlite,
//! and edits stay diff-friendly.
//!
//! JSON is snake_case to match the rest of the app's wire format (analytics /
//! config). Writes are atomic (temp file + rename) so a crash mid-write can't
//! corrupt the list shared between the tracker and Claude.

use std::collections::HashSet;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

/// One user todo. `id` is generated by the frontend (a stable opaque string).
/// `status` is one kanban column: `backlog` | `queue` | `in_progress` |
/// `review` | `done`. The pre-kanban `pending` status is migrated to `backlog`
/// on load (see [`canonical_status`]). Optional fields are omitted from the file
/// when empty to keep hand-edits readable.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Todo {
    pub id: String,
    /// Stable, human-facing task number (like a GitHub issue number) for inline
    /// `#N` references. Assigned once (see [`ensure_numbers`]) and never reused,
    /// so a reference stays valid even after other tasks are deleted. 0 = not yet
    /// assigned (legacy/hand-edited rows; backfilled on the next load/write).
    #[serde(default)]
    pub number: u32,
    pub subject: String,
    #[serde(default)]
    pub description: String,
    pub status: String,
    /// Priority bucket: `high` | `medium` | `low`, or empty = unset. Drives which
    /// tasks the SessionStart hook injects (a min-level threshold) and how verbose
    /// each one is. Empty is omitted from the file so existing todos need no
    /// migration and unprioritized rows stay clean. Keep the value set in lockstep
    /// with [`PRIORITIES`], the cc-todos CLI, and TodoWindow.vue.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub priority: String,
    /// LLM/user time estimate in minutes; None = unestimated.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub estimate_minutes: Option<i64>,
    /// ISO date `YYYY-MM-DD` the user plans to do this; None = unscheduled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduled_for: Option<String>,
    /// Raw plan — written by the USER, never generated by the LLM.
    #[serde(default)]
    pub plan: String,
    /// Project basename this todo belongs to (matches a transcript cwd
    /// basename); None = not tied to a project.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// Project this task was filed FROM (issue #13). The cc-todos CLI sets it
    /// automatically to the originating session's project when a task is filed
    /// against a DIFFERENT project, so the board can show its provenance. None for
    /// same-project or app-created tasks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    /// Discussion thread on this todo (user + Claude). Empty → omitted from the
    /// file so hand-edits and the common no-comment case stay clean.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub comments: Vec<Comment>,
    /// Ids of related todos. Stored one-way per todo; the UI also surfaces the
    /// reverse direction by scanning. Empty → omitted from the file.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub links: Vec<String>,
    /// Ids of todos this one DEPENDS ON — the directed edges of the task graph
    /// (#88). `a.depends_on = [b]` means b must be done before a; b blocks a.
    /// Kept acyclic and within a single project board (enforced by [`add_dep`]).
    /// Distinct from `links`/inline `#N`, which are non-blocking references the
    /// graph draws as a second, dashed edge. Empty → omitted from the file.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub depends_on: Vec<String>,
    /// Who composed this todo: `"user"` (hand-written in the UI) or `"claude"`
    /// (the cc-todos CLI). Empty (legacy rows) renders as a user task — no AI
    /// badge — so existing files need no migration.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub created_by: String,
    #[serde(default)]
    pub created_at: String,
    #[serde(default)]
    pub updated_at: String,
}

/// One comment in a todo's thread. `author` is `"user"` or `"claude"` (a plain
/// string so another source can be added without a migration). `body` is plain
/// text; the UI renders links in it. `id`/`created_at` are set by whoever appends
/// (the frontend or the cc-todos CLI).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Comment {
    pub id: String,
    pub author: String,
    #[serde(default)]
    pub body: String,
    #[serde(default)]
    pub created_at: String,
}

fn default_version() -> u32 {
    1
}

/// The on-disk shape of `todos.json`. `version` lets us migrate the format
/// later; unknown/missing fields default so older or hand-edited files load.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TodoFile {
    #[serde(default = "default_version")]
    pub version: u32,
    #[serde(default)]
    pub todos: Vec<Todo>,
}

impl Default for TodoFile {
    fn default() -> Self {
        TodoFile {
            version: default_version(),
            todos: Vec::new(),
        }
    }
}

/// Read the store. A missing or malformed file yields an empty list rather than
/// an error — the tracker should always present a usable (possibly empty) todo
/// view, and the hook must never fail a session over a bad file. Every loaded
/// status is run through [`canonical_status`] so legacy `pending` rows (written
/// before the kanban columns existed) and any hand-edited values land in a real
/// column instead of vanishing.
pub fn load(path: &Path) -> TodoFile {
    let mut file = match std::fs::read_to_string(path) {
        Ok(s) => serde_json::from_str(&s).unwrap_or_default(),
        Err(_) => TodoFile::default(),
    };
    for t in &mut file.todos {
        t.status = canonical_status(&t.status).to_string();
    }
    file
}

/// Persist the store atomically: write a sibling temp file, then rename over the
/// target (std rename replaces the destination on Windows for files).
pub fn save(path: &Path, file: &TodoFile) -> Result<(), String> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    }
    let json = serde_json::to_string_pretty(file).map_err(|e| e.to_string())?;
    let tmp = path.with_extension("json.tmp");
    std::fs::write(&tmp, json.as_bytes()).map_err(|e| e.to_string())?;
    std::fs::rename(&tmp, path).map_err(|e| e.to_string())?;
    Ok(())
}

/// The largest task number currently assigned (0 if none).
pub fn max_number(file: &TodoFile) -> u32 {
    file.todos.iter().map(|t| t.number).max().unwrap_or(0)
}

/// Assign a stable sequential number to every task that lacks one (`number == 0`),
/// in creation order, continuing after the current max. Returns true if anything
/// changed, so the caller can persist. Numbers are never reused, so an inline
/// `#N` reference stays valid even after other tasks are deleted.
pub fn ensure_numbers(file: &mut TodoFile) -> bool {
    let mut idx: Vec<usize> = file
        .todos
        .iter()
        .enumerate()
        .filter(|(_, t)| t.number == 0)
        .map(|(i, _)| i)
        .collect();
    if idx.is_empty() {
        return false;
    }
    // Deterministic order regardless of vec order: oldest first, id as tiebreak.
    idx.sort_by(|&a, &b| {
        file.todos[a]
            .created_at
            .cmp(&file.todos[b].created_at)
            .then_with(|| file.todos[a].id.cmp(&file.todos[b].id))
    });
    let mut next = max_number(file) + 1;
    for i in idx {
        file.todos[i].number = next;
        next += 1;
    }
    true
}

/// Insert a new todo or replace an existing one (matched by `id`). `created_at`
/// is preserved from the existing row (or stamped `now` for a new one);
/// `updated_at` is always set to `now`. A new task with no `number` (0) gets the
/// next one; replacing a task keeps its existing number if the caller didn't
/// carry it through.
pub fn upsert(file: &mut TodoFile, mut todo: Todo, now: &str) {
    todo.updated_at = now.to_string();
    if let Some(existing) = file.todos.iter_mut().find(|t| t.id == todo.id) {
        todo.created_at = if existing.created_at.is_empty() {
            now.to_string()
        } else {
            existing.created_at.clone()
        };
        if todo.number == 0 {
            todo.number = existing.number;
        }
        // Provenance is set once (by the CLI) and has no UI field, so a UI edit
        // that doesn't carry it must not erase it.
        if todo.from.is_none() {
            todo.from = existing.from.clone();
        }
        *existing = todo;
    } else {
        if todo.created_at.is_empty() {
            todo.created_at = now.to_string();
        }
        if todo.number == 0 {
            todo.number = max_number(file) + 1;
        }
        file.todos.push(todo);
    }
}

/// Remove the todo with this id (no-op if absent).
pub fn delete(file: &mut TodoFile, id: &str) {
    file.todos.retain(|t| t.id != id);
}

/// Set a todo's status and bump `updated_at`. Returns false if no such id.
pub fn set_status(file: &mut TodoFile, id: &str, status: &str, now: &str) -> bool {
    if let Some(t) = file.todos.iter_mut().find(|t| t.id == id) {
        t.status = status.to_string();
        t.updated_at = now.to_string();
        true
    } else {
        false
    }
}

/// The project board a todo belongs to, normalized: a project-less (global) task
/// reads as `""`. Two todos share a board iff this value matches. Used to keep
/// dependency edges within one project (#88).
fn board_of<'a>(t: &'a Todo) -> &'a str {
    t.project.as_deref().unwrap_or("")
}

/// True if a `depends_on` edge from `from_id` to `on_id` would close a cycle,
/// i.e. `on_id` already reaches `from_id` by following `depends_on`. A plain DFS
/// over the current edges; the graph is small (one board) so this stays cheap.
fn dep_reaches(file: &TodoFile, start: &str, target: &str) -> bool {
    let mut stack = vec![start.to_string()];
    let mut seen = std::collections::HashSet::new();
    while let Some(id) = stack.pop() {
        if id == target {
            return true;
        }
        if !seen.insert(id.clone()) {
            continue;
        }
        if let Some(t) = file.todos.iter().find(|t| t.id == id) {
            for d in &t.depends_on {
                stack.push(d.clone());
            }
        }
    }
    false
}

/// Add a dependency edge: `from_id` depends on `on_id` (on_id blocks from_id).
/// Rejects a self-edge, a missing endpoint, a cross-board edge, or an edge that
/// would create a cycle — so the stored graph is always a within-board DAG.
/// Idempotent: re-adding an existing edge is a no-op success. Bumps `updated_at`
/// on the dependent when an edge is actually added.
pub fn add_dep(file: &mut TodoFile, from_id: &str, on_id: &str, now: &str) -> Result<(), String> {
    if from_id == on_id {
        return Err("a task can't depend on itself".into());
    }
    let on = file
        .todos
        .iter()
        .find(|t| t.id == on_id)
        .ok_or_else(|| format!("no task with id {on_id}"))?;
    let from = file
        .todos
        .iter()
        .find(|t| t.id == from_id)
        .ok_or_else(|| format!("no task with id {from_id}"))?;
    if board_of(from) != board_of(on) {
        return Err("dependencies must stay within one project board".into());
    }
    // A cycle forms if `on_id` can already reach `from_id` via depends_on.
    if dep_reaches(file, on_id, from_id) {
        return Err("that dependency would create a cycle".into());
    }
    let from = file.todos.iter_mut().find(|t| t.id == from_id).unwrap();
    if !from.depends_on.iter().any(|d| d == on_id) {
        from.depends_on.push(on_id.to_string());
        from.updated_at = now.to_string();
    }
    Ok(())
}

/// Remove a dependency edge (`from_id` no longer depends on `on_id`). Returns
/// true if an edge was actually removed. Bumps `updated_at` on change.
pub fn remove_dep(file: &mut TodoFile, from_id: &str, on_id: &str, now: &str) -> bool {
    if let Some(from) = file.todos.iter_mut().find(|t| t.id == from_id) {
        let before = from.depends_on.len();
        from.depends_on.retain(|d| d != on_id);
        if from.depends_on.len() != before {
            from.updated_at = now.to_string();
            return true;
        }
    }
    false
}

// --- Inline-ref migration (#63): bare `#N` → explicit `t#N` --------------------
//
// A bare `#N` in prose overwhelmingly means a GitHub PR/issue; when its number
// collided with a task's, the old linker silently pointed at the wrong task. The
// UI/graph/CLI now link ONLY the explicit `t#N` form, so this migration rewrites
// the genuine task references already sitting in stored text to `t#N` (otherwise
// they'd go dark). It is deliberately conservative — a `#N` is rewritten only when
// it looks like a real task reference, never when it looks like a PR — and every
// migration takes a backup first so a wrong guess is one click from undo.

/// Words that, immediately before a `#N`, mark it as a GitHub PR/issue reference
/// (leave it a bare `#N`) rather than a task reference.
const PR_WORDS: [&str; 6] = ["pr", "pull", "request", "gh", "issue", "mr"];

/// True if the text right before the `#` at `hash_idx` ends in a PR-indicator word
/// (case-insensitive, whole word), e.g. `PR #14`, `pull request #3`, `GH #7`.
fn preceded_by_pr_word(text: &str, hash_idx: usize) -> bool {
    let before = text[..hash_idx].trim_end_matches([' ', '\t', ':', '-']);
    let lower = before.to_lowercase();
    PR_WORDS.iter().any(|w| {
        lower.strip_suffix(w).map_or(false, |head| {
            // whole word: nothing before, or a non-alphanumeric separator
            head.chars().last().map_or(true, |c| !c.is_alphanumeric())
        })
    })
}

/// Rewrite bare `#N` task references to the explicit `t#N` form within one text
/// field. A `#N` is converted only when: N is a known task number (`known`); it is
/// not the tail of a word or already `t#N` (any letter/digit immediately before
/// `#` disqualifies it); and it is not preceded by a PR-indicator word. Returns the
/// rewritten text and how many references were converted.
pub fn rewrite_inline_refs(text: &str, known: &HashSet<u32>) -> (String, usize) {
    let chars: Vec<(usize, char)> = text.char_indices().collect();
    let mut out = String::with_capacity(text.len() + 8);
    let mut count = 0usize;
    let mut k = 0usize;
    while k < chars.len() {
        let (byte_idx, c) = chars[k];
        if c == '#' {
            let mut m = k + 1;
            while m < chars.len() && chars[m].1.is_ascii_digit() {
                m += 1;
            }
            if m > k + 1 {
                // A letter/digit right before `#` means a word tail (`part#5`) or an
                // already-migrated `t#5` — either way, not a bare ref to rewrite.
                let word_tail = k > 0 && chars[k - 1].1.is_alphanumeric();
                if !word_tail && !preceded_by_pr_word(text, byte_idx) {
                    let digits: String = chars[k + 1..m].iter().map(|(_, ch)| *ch).collect();
                    if matches!(digits.parse::<u32>(), Ok(n) if known.contains(&n)) {
                        out.push('t');
                        out.push('#');
                        out.push_str(&digits);
                        count += 1;
                        k = m;
                        continue;
                    }
                }
            }
        }
        out.push(c);
        k += 1;
    }
    (out, count)
}

/// Outcome of a migration pass: total references rewritten and how many tasks had
/// at least one field changed.
#[derive(Debug, Clone, Copy, Serialize, Default)]
pub struct MigrationStats {
    pub refs: usize,
    pub tasks: usize,
}

/// Rewrite bare `#N` → `t#N` across every task's description, plan and comment
/// bodies (the fields the UI/graph tokenize into links). Subjects are left alone —
/// they render as plain titles, never as links. Timestamps are NOT bumped: this is
/// a mechanical text migration, not a user edit, so it must not reorder the board.
pub fn migrate_refs(file: &mut TodoFile) -> MigrationStats {
    let known: HashSet<u32> = file.todos.iter().map(|t| t.number).filter(|n| *n > 0).collect();
    let mut stats = MigrationStats::default();
    for t in &mut file.todos {
        let mut touched = 0usize;
        let (desc, n) = rewrite_inline_refs(&t.description, &known);
        if n > 0 {
            t.description = desc;
            touched += n;
        }
        let (plan, n) = rewrite_inline_refs(&t.plan, &known);
        if n > 0 {
            t.plan = plan;
            touched += n;
        }
        for c in &mut t.comments {
            let (body, n) = rewrite_inline_refs(&c.body, &known);
            if n > 0 {
                c.body = body;
                touched += n;
            }
        }
        if touched > 0 {
            stats.refs += touched;
            stats.tasks += 1;
        }
    }
    stats
}

// --- Backups (safety net for the migration + any risky bulk edit) --------------

/// Where timestamped backups of `todos.json` live: a `backups/` dir beside it.
pub fn backup_dir(todos_path: &Path) -> PathBuf {
    todos_path
        .parent()
        .map(|d| d.join("backups"))
        .unwrap_or_else(|| PathBuf::from("backups"))
}

/// Metadata for one backup file, for the settings UI (name + when it was taken).
#[derive(Debug, Clone, Serialize)]
pub struct BackupInfo {
    pub name: String,
    pub when_ms: u64,
}

/// Copy the current `todos.json` to a timestamped file under [`backup_dir`],
/// returning the backup's file name. Fails if the source can't be read.
pub fn backup(todos_path: &Path) -> Result<String, String> {
    let content = std::fs::read(todos_path).map_err(|e| e.to_string())?;
    let dir = backup_dir(todos_path);
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    let stamp = chrono::Local::now().format("%Y%m%d-%H%M%S").to_string();
    let name = format!("todos-{stamp}.json");
    std::fs::write(dir.join(&name), &content).map_err(|e| e.to_string())?;
    Ok(name)
}

/// The most recent backup (by file mtime), or None if none exist.
pub fn latest_backup(todos_path: &Path) -> Option<BackupInfo> {
    let dir = backup_dir(todos_path);
    let mut best: Option<(SystemTime, String)> = None;
    for entry in std::fs::read_dir(&dir).ok()?.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        if !name.starts_with("todos-") || !name.ends_with(".json") {
            continue;
        }
        let Ok(mtime) = entry.metadata().and_then(|m| m.modified()) else {
            continue;
        };
        if best.as_ref().map_or(true, |(t, _)| mtime > *t) {
            best = Some((mtime, name));
        }
    }
    best.map(|(t, name)| BackupInfo {
        name,
        when_ms: t
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_millis() as u64)
            .unwrap_or(0),
    })
}

/// Read and validate a backup by file name, returning its parsed store. The name
/// must be a bare file name inside [`backup_dir`] (guards against path traversal),
/// and its content must parse as a [`TodoFile`], so a restore can't install junk.
pub fn read_backup(todos_path: &Path, name: &str) -> Result<TodoFile, String> {
    if Path::new(name).file_name().map_or(true, |f| f != name) {
        return Err("invalid backup name".into());
    }
    let src = backup_dir(todos_path).join(name);
    let content = std::fs::read_to_string(&src).map_err(|e| e.to_string())?;
    let mut file: TodoFile =
        serde_json::from_str(&content).map_err(|e| format!("backup is not a valid todo file: {e}"))?;
    for t in &mut file.todos {
        t.status = canonical_status(&t.status).to_string();
    }
    Ok(file)
}

/// The kanban columns, left to right. The frontend mirrors this order; the hook
/// only cares whether a status is `done`.
pub const STATUSES: [&str; 5] = ["backlog", "queue", "in_progress", "review", "done"];

/// Valid status values. Used by the command layer to reject bad input before it
/// reaches the file (which Claude and the hook also read).
pub fn is_valid_status(status: &str) -> bool {
    STATUSES.contains(&status)
}

/// Priority buckets, most to least important. The hook ranks by this order and
/// the settings threshold names one of these (plus "all"). Mirrored in the
/// cc-todos CLI and TodoWindow.vue.
pub const PRIORITIES: [&str; 3] = ["high", "medium", "low"];

/// Valid priority values: one of [`PRIORITIES`] or empty (unset). The command
/// layer rejects anything else before it reaches the shared file.
pub fn is_valid_priority(priority: &str) -> bool {
    priority.is_empty() || PRIORITIES.contains(&priority)
}

/// Map a raw status onto a real kanban column. The pre-kanban `pending` status
/// becomes `backlog`; any unrecognized value (a typo, a hand-edit, or a status
/// from a future version) also falls back to `backlog` so the todo still shows
/// up as actionable rather than disappearing from every column.
pub fn canonical_status(status: &str) -> &str {
    if is_valid_status(status) {
        status
    } else {
        "backlog"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn todo(id: &str, status: &str) -> Todo {
        Todo {
            id: id.to_string(),
            number: 0,
            subject: format!("subject {id}"),
            description: String::new(),
            status: status.to_string(),
            priority: String::new(),
            estimate_minutes: None,
            scheduled_for: None,
            plan: String::new(),
            project: None,
            from: None,
            comments: Vec::new(),
            links: Vec::new(),
            depends_on: Vec::new(),
            created_by: String::new(),
            created_at: String::new(),
            updated_at: String::new(),
        }
    }

    fn known(nums: &[u32]) -> HashSet<u32> {
        nums.iter().copied().collect()
    }

    #[test]
    fn rewrite_converts_plain_task_ref() {
        let k = known(&[58, 52]);
        let (out, n) = rewrite_inline_refs("хвост #58, см. #52", &k);
        assert_eq!(out, "хвост t#58, см. t#52");
        assert_eq!(n, 2);
    }

    #[test]
    fn rewrite_skips_pr_and_unknown_and_migrated() {
        let k = known(&[63, 104]);
        // PR-worded → left as prose; unknown number → left; already t#N → untouched.
        let (out, n) =
            rewrite_inline_refs("merged PR #104, pull request #63, gone #999, done t#63", &k);
        assert_eq!(out, "merged PR #104, pull request #63, gone #999, done t#63");
        assert_eq!(n, 0);
    }

    #[test]
    fn rewrite_skips_word_tail_but_takes_bracketed() {
        let k = known(&[5]);
        // `abc#5` is a word tail (not a ref); `(#5)` is a real ref.
        let (out, n) = rewrite_inline_refs("abc#5 and (#5)", &k);
        assert_eq!(out, "abc#5 and (t#5)");
        assert_eq!(n, 1);
    }

    #[test]
    fn migrate_refs_covers_description_plan_and_comments() {
        let mut f = TodoFile::default();
        let mut a = todo("a", "backlog");
        a.number = 1;
        a.description = "blocks #2".into();
        a.plan = "after #3 and PR #2".into();
        a.comments = vec![Comment {
            id: "c1".into(),
            author: "user".into(),
            body: "ref #3".into(),
            created_at: String::new(),
        }];
        let mut b = todo("b", "backlog");
        b.number = 2;
        let mut c = todo("c", "backlog");
        c.number = 3;
        f.todos = vec![a, b, c];

        let stats = migrate_refs(&mut f);
        assert_eq!(stats.tasks, 1);
        assert_eq!(stats.refs, 3); // desc #2, plan #3, comment #3 — plan's "PR #2" skipped
        assert_eq!(f.todos[0].description, "blocks t#2");
        assert_eq!(f.todos[0].plan, "after t#3 and PR #2");
        assert_eq!(f.todos[0].comments[0].body, "ref t#3");
        // A mechanical migration must not bump timestamps (no board reorder).
        assert!(f.todos[0].updated_at.is_empty());
    }

    #[test]
    fn backup_then_restore_round_trips() {
        let dir = std::env::temp_dir().join(format!("ct-todos-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("todos.json");
        let mut f = TodoFile::default();
        let mut a = todo("a", "review");
        a.number = 1;
        f.todos = vec![a];
        save(&path, &f).unwrap();

        let name = backup(&path).unwrap();
        assert!(name.starts_with("todos-") && name.ends_with(".json"));
        assert_eq!(latest_backup(&path).unwrap().name, name);

        let restored = read_backup(&path, &name).unwrap();
        assert_eq!(restored.todos.len(), 1);
        assert_eq!(restored.todos[0].status, "review");
        // Path-traversal names are rejected.
        assert!(read_backup(&path, "../todos.json").is_err());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn upsert_adds_then_updates_in_place() {
        let mut f = TodoFile::default();
        upsert(&mut f, todo("a", "backlog"), "T1");
        assert_eq!(f.todos.len(), 1);
        assert_eq!(f.todos[0].created_at, "T1");
        assert_eq!(f.todos[0].updated_at, "T1");

        // Updating the same id replaces it and preserves created_at.
        let mut updated = todo("a", "done");
        updated.subject = "changed".into();
        upsert(&mut f, updated, "T2");
        assert_eq!(f.todos.len(), 1);
        assert_eq!(f.todos[0].status, "done");
        assert_eq!(f.todos[0].subject, "changed");
        assert_eq!(f.todos[0].created_at, "T1"); // preserved
        assert_eq!(f.todos[0].updated_at, "T2"); // bumped
    }

    #[test]
    fn upsert_assigns_number_to_new_tasks() {
        let mut f = TodoFile::default();
        upsert(&mut f, todo("a", "backlog"), "T1");
        upsert(&mut f, todo("b", "backlog"), "T2");
        assert_eq!(f.todos[0].number, 1);
        assert_eq!(f.todos[1].number, 2);

        // Replacing a task keeps its number even if the caller passes 0.
        let mut updated = todo("a", "done");
        updated.number = 0;
        upsert(&mut f, updated, "T3");
        assert_eq!(f.todos.iter().find(|t| t.id == "a").unwrap().number, 1);

        // A caller that carries a non-zero number is respected.
        let mut c = todo("c", "backlog");
        c.number = 0;
        upsert(&mut f, c, "T4");
        assert_eq!(f.todos.iter().find(|t| t.id == "c").unwrap().number, 3);
    }

    #[test]
    fn ensure_numbers_backfills_in_creation_order_and_continues_after_max() {
        let mut f = TodoFile::default();
        // Pre-existing numbered task + two legacy tasks (number 0).
        let mut numbered = todo("x", "backlog");
        numbered.number = 5;
        numbered.created_at = "2026-01-01".into();
        let mut older = todo("a", "backlog");
        older.created_at = "2026-02-01".into();
        let mut newer = todo("b", "backlog");
        newer.created_at = "2026-03-01".into();
        f.todos = vec![newer, numbered, older];

        assert!(ensure_numbers(&mut f));
        // Continues after the max (5); oldest legacy gets the lower number.
        assert_eq!(f.todos.iter().find(|t| t.id == "a").unwrap().number, 6);
        assert_eq!(f.todos.iter().find(|t| t.id == "b").unwrap().number, 7);
        assert_eq!(f.todos.iter().find(|t| t.id == "x").unwrap().number, 5);
        // Idempotent once everything is numbered.
        assert!(!ensure_numbers(&mut f));
    }

    #[test]
    fn delete_removes_by_id() {
        let mut f = TodoFile::default();
        upsert(&mut f, todo("a", "backlog"), "T1");
        upsert(&mut f, todo("b", "backlog"), "T1");
        delete(&mut f, "a");
        assert_eq!(f.todos.len(), 1);
        assert_eq!(f.todos[0].id, "b");
        delete(&mut f, "missing"); // no-op
        assert_eq!(f.todos.len(), 1);
    }

    #[test]
    fn set_status_updates_and_reports_missing() {
        let mut f = TodoFile::default();
        upsert(&mut f, todo("a", "backlog"), "T1");
        assert!(set_status(&mut f, "a", "in_progress", "T2"));
        assert_eq!(f.todos[0].status, "in_progress");
        assert_eq!(f.todos[0].updated_at, "T2");
        assert!(!set_status(&mut f, "missing", "done", "T3"));
    }

    #[test]
    fn status_validation() {
        assert!(is_valid_status("backlog"));
        assert!(is_valid_status("queue"));
        assert!(is_valid_status("in_progress"));
        assert!(is_valid_status("review"));
        assert!(is_valid_status("done"));
        // Legacy and bogus values are not accepted at the command layer.
        assert!(!is_valid_status("pending"));
        assert!(!is_valid_status("Done"));
        assert!(!is_valid_status("archived"));
    }

    #[test]
    fn priority_validation_allows_buckets_and_unset() {
        assert!(is_valid_priority("high"));
        assert!(is_valid_priority("medium"));
        assert!(is_valid_priority("low"));
        assert!(is_valid_priority("")); // unset is valid
        assert!(!is_valid_priority("urgent"));
        assert!(!is_valid_priority("High"));
    }

    #[test]
    fn priority_empty_is_omitted_from_file() {
        let dir = std::env::temp_dir();
        let path = dir.join("cut_todos_priority_test.json");
        let _ = std::fs::remove_file(&path);

        let mut f = TodoFile::default();
        let mut a = todo("a", "backlog");
        a.priority = "high".into();
        let b = todo("b", "backlog"); // priority unset
        upsert(&mut f, a, "T1");
        upsert(&mut f, b, "T1");
        save(&path, &f).unwrap();

        let raw = std::fs::read_to_string(&path).unwrap();
        assert!(raw.contains("\"priority\": \"high\""));
        // Exactly one priority field — the unset one is omitted.
        assert_eq!(raw.matches("\"priority\"").count(), 1);

        let back = load(&path);
        assert_eq!(back.todos.iter().find(|t| t.id == "a").unwrap().priority, "high");
        assert_eq!(back.todos.iter().find(|t| t.id == "b").unwrap().priority, "");
        let _ = std::fs::remove_file(&path);
    }

    fn board_todo(id: &str, project: Option<&str>) -> Todo {
        let mut t = todo(id, "backlog");
        t.project = project.map(|s| s.to_string());
        t
    }

    #[test]
    fn add_dep_records_edge_and_is_idempotent() {
        let mut f = TodoFile::default();
        f.todos = vec![board_todo("a", Some("p")), board_todo("b", Some("p"))];
        // a depends on b.
        assert!(add_dep(&mut f, "a", "b", "T2").is_ok());
        let a = f.todos.iter().find(|t| t.id == "a").unwrap();
        assert_eq!(a.depends_on, vec!["b".to_string()]);
        assert_eq!(a.updated_at, "T2");
        // Re-adding the same edge is a no-op success (no duplicate).
        assert!(add_dep(&mut f, "a", "b", "T3").is_ok());
        assert_eq!(
            f.todos.iter().find(|t| t.id == "a").unwrap().depends_on.len(),
            1
        );
    }

    #[test]
    fn add_dep_rejects_self_missing_cross_board_and_cycle() {
        let mut f = TodoFile::default();
        f.todos = vec![
            board_todo("a", Some("p")),
            board_todo("b", Some("p")),
            board_todo("c", Some("q")),
        ];
        assert!(add_dep(&mut f, "a", "a", "T").is_err()); // self
        assert!(add_dep(&mut f, "a", "missing", "T").is_err()); // missing endpoint
        assert!(add_dep(&mut f, "a", "c", "T").is_err()); // cross-board (p vs q)
        // Build a→b, then b→a must be rejected as a cycle.
        assert!(add_dep(&mut f, "a", "b", "T").is_ok());
        assert!(add_dep(&mut f, "b", "a", "T").is_err());
        // The rejected edge left b clean.
        assert!(f.todos.iter().find(|t| t.id == "b").unwrap().depends_on.is_empty());
    }

    #[test]
    fn add_dep_rejects_transitive_cycle() {
        let mut f = TodoFile::default();
        f.todos = vec![
            board_todo("a", Some("p")),
            board_todo("b", Some("p")),
            board_todo("c", Some("p")),
        ];
        // a→b→c, then c→a would close the loop.
        assert!(add_dep(&mut f, "a", "b", "T").is_ok());
        assert!(add_dep(&mut f, "b", "c", "T").is_ok());
        assert!(add_dep(&mut f, "c", "a", "T").is_err());
    }

    #[test]
    fn add_dep_allows_edges_between_global_tasks() {
        let mut f = TodoFile::default();
        // Two project-less tasks share the "" board.
        f.todos = vec![board_todo("a", None), board_todo("b", None)];
        assert!(add_dep(&mut f, "a", "b", "T").is_ok());
    }

    #[test]
    fn remove_dep_reports_change() {
        let mut f = TodoFile::default();
        f.todos = vec![board_todo("a", Some("p")), board_todo("b", Some("p"))];
        add_dep(&mut f, "a", "b", "T").unwrap();
        assert!(remove_dep(&mut f, "a", "b", "T2"));
        assert!(f.todos.iter().find(|t| t.id == "a").unwrap().depends_on.is_empty());
        // Removing a non-existent edge reports no change.
        assert!(!remove_dep(&mut f, "a", "b", "T3"));
    }

    #[test]
    fn depends_on_empty_is_omitted_from_file() {
        let dir = std::env::temp_dir();
        let path = dir.join("cut_todos_deps_test.json");
        let _ = std::fs::remove_file(&path);
        let mut f = TodoFile::default();
        f.todos = vec![board_todo("a", Some("p")), board_todo("b", Some("p"))];
        add_dep(&mut f, "a", "b", "T").unwrap();
        save(&path, &f).unwrap();
        let raw = std::fs::read_to_string(&path).unwrap();
        assert!(raw.contains("\"depends_on\""));
        // Only the dependent task serializes the field; b (empty) omits it.
        assert_eq!(raw.matches("\"depends_on\"").count(), 1);
        let back = load(&path);
        assert_eq!(back.todos.iter().find(|t| t.id == "a").unwrap().depends_on, vec!["b".to_string()]);
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn canonical_status_migrates_legacy_and_unknown() {
        assert_eq!(canonical_status("in_progress"), "in_progress");
        assert_eq!(canonical_status("review"), "review");
        // Pre-kanban status and anything unrecognized collapse to backlog.
        assert_eq!(canonical_status("pending"), "backlog");
        assert_eq!(canonical_status("whatever"), "backlog");
    }

    #[test]
    fn load_migrates_legacy_pending_status() {
        let dir = std::env::temp_dir();
        let path = dir.join("cut_todos_migrate_test.json");
        let _ = std::fs::remove_file(&path);

        // A file written before the kanban columns existed: status "pending".
        let raw = r#"{"version":1,"todos":[{"id":"a","subject":"s","status":"pending","plan":""}]}"#;
        std::fs::write(&path, raw).unwrap();

        let f = load(&path);
        assert_eq!(f.todos.len(), 1);
        assert_eq!(f.todos[0].status, "backlog");
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn load_missing_file_is_empty_default() {
        let f = load(Path::new("does-not-exist-12345.json"));
        assert_eq!(f.version, 1);
        assert!(f.todos.is_empty());
    }

    #[test]
    fn save_then_load_roundtrips_and_omits_empty_optionals() {
        let dir = std::env::temp_dir();
        let path = dir.join("cut_todos_roundtrip_test.json");
        let _ = std::fs::remove_file(&path);

        let mut f = TodoFile::default();
        let mut t = todo("a", "queue");
        t.estimate_minutes = Some(30);
        t.project = Some("my-proj".into());
        upsert(&mut f, t, "T1");
        save(&path, &f).unwrap();

        // Optional None fields are skipped in the serialized form.
        let raw = std::fs::read_to_string(&path).unwrap();
        assert!(raw.contains("\"estimate_minutes\": 30"));
        assert!(!raw.contains("scheduled_for"));

        let back = load(&path);
        assert_eq!(back.todos.len(), 1);
        assert_eq!(back.todos[0].estimate_minutes, Some(30));
        assert_eq!(back.todos[0].project.as_deref(), Some("my-proj"));
        let _ = std::fs::remove_file(&path);
    }
}
